server:
  port: 0
spring:
  application:
    name: catalog-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # Intervalo de renovación de arrendamiento en segundos
    lease-expiration-duration-in-seconds: 10 # Duración de expiración del arrendamiento en segundos